name: Beta Deployment
on:
  push:
    branches:
      - beta-*
jobs:
  build-io:
    name: Beta Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Ensure python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt; pip install pylint==${{ secrets.PYLINT_VERSION }}
      - name: Run lint
        run: pylint redis_stomp -E
      - name: Create tag
        id: docker_tag
        run: |
          commit_tag=${GITHUB_REF#refs/*/}
          echo "tag=${commit_tag}-${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT
      - name: Verify tag
        run: echo ${{ steps.docker_tag.outputs.tag }}
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          no-cache: true
          build-args: |
            RUN_AS_USER=plaid
          tags: us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/redistomp:latest,us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/redistomp:${{ steps.docker_tag.outputs.tag }}

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: PlaidCloud/plaid-tenant-infrastructure
          ref: beta
          fetch-depth: '1'
          path: infrastructure
          token: ${{ secrets.GITOPS_REPO_ACCESS }}

      - name: Update Control Plane & Tenant Image
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: PlaidCloud/plaid-tenant-infrastructure
          branch: beta
          message: 'Update STOMP Image to ${{ steps.docker_tag.outputs.tag }}'
          token: ${{ secrets.GITOPS_REPO_ACCESS }}
          workDir: infrastructure
          changes: |
            {
              "controlplane/values.yaml": {
                "apps.stomp.image": "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/redistomp:${{ steps.docker_tag.outputs.tag }}"
              },
              "tenants/values.yaml": {
                "apps.stomp.image": "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/redistomp:${{ steps.docker_tag.outputs.tag }}"
              }
            }
