name: IO Deployment
on:
  push:
    branches:
      - main
jobs:
  build-io:
    name: IO Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Ensure python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt; pip install pylint==${{ secrets.PYLINT_VERSION }}
      - name: Run lint
        run: pylint redis_stomp -E
      - name: Create tag
        id: docker_tag
        run: |
          commit_tag=${GITHUB_REF#refs/*/}
          echo "tag=${commit_tag}-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Verify tag
        run: echo ${{ steps.docker_tag.outputs.tag }}
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          no-cache: true
          build-args: |
            RUN_AS_USER=plaid
          tags: gcr.io/plaidcloud-build/redistomp:latest,gcr.io/plaidcloud-build/redistomp:${{ steps.docker_tag.outputs.tag }}

      - name: Checkout GitOps Repository
        uses: actions/checkout@v3
        with:
          repository: PlaidCloud/plaid-tenant-applications
          ref: master
          fetch-depth: '1'
          path: infrastructure
          token: ${{ secrets.GITOPS_REPO_ACCESS }}

      - name: Update Control Plane Image
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'controlplane/environment-values/ci-cluster.yaml'
          repository: PlaidCloud/plaid-tenant-applications
          branch: master
          message: 'Update Control Plane Image to ${{ steps.docker_tag.outputs.tag }}'
          token: ${{ secrets.GITOPS_REPO_ACCESS }}
          workDir: infrastructure
          changes: |
            {
              "apps.stomp.image": "gcr.io/plaidcloud-build/redistomp:${{ steps.docker_tag.outputs.tag }}"
            }

      - name: Update Tenant Image
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'tenants/values.yaml'
          repository: PlaidCloud/plaid-tenant-applications
          branch: master
          message: 'Update Tenant Image to ${{ steps.docker_tag.outputs.tag }}'
          token: ${{ secrets.GITOPS_REPO_ACCESS }}
          workDir: infrastructure
          changes: |
            {
              "apps.stomp.image": "gcr.io/plaidcloud-build/redistomp:${{ steps.docker_tag.outputs.tag }}"
            }

      - name: Trigger ArgoCD Sync for CI Control Plane App
        uses: clowdhaus/argo-cd-action/@main
        timeout-minutes: 1
        env:
          ARGOCD_SERVER: deploy.plaidcloud.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This might not be needed - Mostly used to avoid rate limiting
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        with:
          command: app sync ci-cluster-controlplane
          options: --grpc-web --prune
